---
  - name: install package
    apt:
      name: haproxy
      state: latest
      update_cache: true
   
  - name: render configuration
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify:
      - reload haproxy

  - name: setup nonlocal binding
    sysctl:
      name: net.ipv4.ip_nonlocal_bind
      value: 1

  - name: ensure service is running
    service:
      name: haproxy
      state: started
