---
  - name: run container
    docker_container:
      name: jaeger
      image: jaegertracing/all-in-one
      state: started
      detach: yes
      restart_policy: unless-stopped
      env:
        COLLECTOR_ZIPKIN_HTTP_PORT: 9422
      ports:
        - 9422:9422
        - 5775:5775/udp 
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
